CREATE TABLE Customer (
cid INT PRIMARY KEY AUTO_INCREMENT,
cusername VARCHAR(50) NOT NULL UNIQUE,
cpassword VARCHAR(30) NOT NULL,
ccontact VARCHAR(10) NOT NULL,
caddress VARCHAR(100) NOT NULL
);

CREATE TABLE Service (
sid INT PRIMARY KEY AUTO_INCREMENT,
sname VARCHAR(100) NOT NULL UNIQUE,
scharge DOUBLE NOT NULL
);

CREATE TABLE Technician (
tid INT PRIMARY KEY AUTO_INCREMENT,
tusername VARCHAR(100) NOT NULL UNIQUE,
tpassword VARCHAR(100) NOT NULL,
taddress VARCHAR(100) NOT NULL,
tcontact VARCHAR(10) NOT NULL,
tisAssigned TINYINT NOT NULL DEFAULT 0
);

CREATE TABLE Appointment (
aid INT PRIMARY KEY AUTO_INCREMENT,
cid INT NOT NULL,
sid INT NOT NULL,
tid INT NOT NULL,
adate DATETIME NOT NULL,
FOREIGN KEY (cid) REFERENCES Customer(cid),
FOREIGN KEY (sid) REFERENCES Service(sid),
FOREIGN KEY (tid) REFERENCES Technician(tid)
);

CREATE TABLE Admin (
id INT PRIMARY KEY AUTO_INCREMENT,
username VARCHAR(50) NOT NULL UNIQUE,
password VARCHAR(50) NOT NULL
);

